services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: property_user
      POSTGRES_PASSWORD: property_pass
      POSTGRES_DB: property_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend-python
    container_name: pm-backend-python
    ports:
      - "5000:5000"          # host:container
    env_file:
      - ./backend-python/.env       # uses Python backend .env
    depends_on:
      - db
    volumes:
      - ./backend-python/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
    container_name: pm-frontend
    ports:
      - "5173:80"            # browser hits http://localhost:5173
    depends_on:
      - backend

volumes:
  postgres_data:
